server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_test
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
